version: '3'

services:
  packagemate-server:
    build:
      context: api_server
      dockerfile: Dockerfile
    image: packagemate-server
    container_name: packagemate-server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
      - UPS_ACCESS_KEY=$UPS_ACCESS_KEY
      - USPS_USERNAME=$USPS_USERNAME
    networks:
      - app-network
    # this will work as long as you haven't changed the mongodb port from the default
    # if you have, change it here as well
    command: ./wait-for.sh db:27017 -- npm start
  packagemate-client:
    build:
      context: client
      dockerfile: Dockerfile
    image: packagemate-client
    container_name: packagemate-client
    restart: unless-stopped
    env_file: .env
    depends_on: 
      - packagemate-server
      - db
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 
      - UPS_ACCESS_KEY=$UPS_ACCESS_KEY
      - USPS_USERNAME=$USPS_USERNAME
    ports:
      # this is the port of the main app, by default, port 80 is
      # exposed on the host machine (localhost or 127.0.0.1)
      - "80:3000"
    networks:
      - app-network
    command: npm start
    stdin_open: true
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:  
      - dbdata:/data/db   
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  